git-go-clone works great

diff --git a/src/git-go-clone b/src/git-go-clone
--- a/src/git-go-clone
+++ b/src/git-go-clone
@@ -1,10 +1,9 @@
 #!/usr/bin/env bash
 
-set -e
+set -e # Exit on error
 
-declare SCRIPT_PATH=$(realpath "$(dirname $0)")
+SCRIPT_PATH=$(realpath "$(dirname $0)")
 
-# Source the script to test
 source "$(realpath ${SCRIPT_PATH}/functions/remote_to_path.sh)"
 
 # Function to display usage information
@@ -31,6 +30,8 @@ while [[ "$#" -gt 0 ]]; do
         *)
             if [[ "$1" == -* ]]; then
                 OPTIONS="$OPTIONS $1"
+            elif [[ "$1" == --* ]]; then
+                OPTIONS="$OPTIONS $1"
             elif [ -z "$REPO_URL" ]; then
                 REPO_URL="$1"
             else
@@ -48,15 +49,29 @@ if [ -z "$REPO_URL" ]; then
     usage
 fi
 
+
+# Define a prefix of ${GOPATH}. If GOPATH is not set, set to ${HOME}.
+PREFIX=${GOPATH:-$HOME}/src
+
+# Get the path to the repository
+REPO_PATH="${PREFIX}/$(remote_to_path ${REPO_URL})"
+
+# Check if the repository already exists
+if [ -d "${REPO_PATH}" ]; then
+    echo "Error: Repository already exists at ${REPO_PATH}"
+    echo "cd ${REPO_PATH}"
+    exit 1
+fi
+
 # Handle dry-run option
 if [ "$DRY_RUN" = true ]; then
     echo "Dry run: Repository URL is $REPO_URL"
-    echo "git clone ${OPTIONS} ${REPO_URL}"
+    echo "git clone ${OPTIONS} ${REPO_URL} ${REPO_PATH}"
     exit 0
 fi
 
 # Clone the repository with options
-git clone $OPTIONS "$REPO_URL" || {
+git clone $OPTIONS "$REPO_URL" "${REPO_PATH}" || {
     echo "Error: Failed to clone repository."
     exit 1
 }
